// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkqsvmvkobbybrrosvyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrcXN2bXZrb2JieWJycm9zdnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1ODEzMDIsImV4cCI6MjA4MDE1NzMwMn0.qPYRg7juLsAOyJBu3_2ZouBrf4B8IZYGsSeJWRdPmcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});